#! /bin/sh
### BEGIN INIT INFO
# Provides:          CEC Daemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CEC Daemon
# Description:       CEC Daemon
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="CEC Daemon"
NAME="$(basename "$0")"
DAEMON=/usr/bin/cec-daemon
DAEMON_USER=root
PIDFILE="/var/run/${NAME}.pid"
SCRIPTNAME="/etc/init.d/${NAME}"

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

log_with() {
  [ "${VERBOSE}" != no ] && "$@"
}

check_status() {
  status="$1"
  log_with log_end_msg "${status}"
  [ "${status}" != 0 ] && exit 1
}

start() {
  log_with log_daemon_msg "Starting ${DESC}" "${NAME}"
  start-stop-daemon --start --background --pidfile "${PIDFILE}" --make-pidfile \
    --user "${DAEMON_USER}" --chuid "${DAEMON_USER}" --exec "${DAEMON}"
  check_status $?
}

stop() {
  log_with log_daemon_msg "Stopping ${DESC}" "${NAME}"
  start-stop-daemon --stop --pidfile "${PIDFILE}" --retry 10
  check_status $?
}


case "$1" in
start) start ;;
stop) stop ;;
status) status_of_proc "${DAEMON}" "${NAME}"; exit $? ;;
restart | force-reload) stop && start ;;
*) echo "Usage: ${SCRIPTNAME} {start|stop|status|restart|force-reload}" >&2 && exit 3 ;;
esac

exit 0
